# Generated by Django 5.1.6 on 2025-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Successful", "Successful"),
                            ("Failed", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
